version: "3.9"
services:
  
  blockscanner:
    image: alethio/ethereum-lite-explorer
    ports: 
      - 80:80
    environment:
      - APP_NODE_URL=http://localhost:8545

  graphdb:
    build:
      context: .
      dockerfile: Dockerfile
      target: graphdb
      args:
        version: 10.2.2
    environment:
      GDB_JAVA_OPTS: >-
        -Xmx2g -Xms2g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    ports:
      - 7200:7200
      - 7300:7300
    volumes:
      - ./graphdb-data:/opt/graphdb/home